version: "3.9"

services:
  api:
    build: .
    restart: always
    container_name: task_management_api
    ports:
      - "3000:3000"
    volumes:
      - .:/task_management
    command: >
      sh -c "npm run start:dev"
    env_file:
      - ./.env
    environment:
      - ADMIN_DATABASE_URL=postgres://postgres:postgres@db/task_management_db
    depends_on:
      - db

  db:
    image: postgres:15.1-alpine
    container_name: task_management_db
    volumes:
      - db-data:/var/lib/postgresql/data/
    ports:
      - "5435:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task_management_db
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB'
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: task_management_db_admin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: abram@govahq.com
      PGADMIN_DEFAULT_PASSWORD: abram
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  db-data:
  pgadmin-data:
